Nombre: Samuel\
Apellidos: Martín Morales\
Correo: alu0101359526@ull.edu.es

### **EJERCICIOS TEÓRICOS**

### Ejercicio 1:
¿Por qué usar programación como Python, y en concreto Pandas, y no directamente una hoja de cálculo?

Es más útil el uso de la programación con Python y en concreto con Pandas, debido a que Pandas proporciona ciertas\
funciones y objetos que son necesarias para tratar los dataframe con grandes cantidades de datos de una manera mucho más cómoda y sencilla\
que si se tratara de una hoja de cálculo. Esto último, sería muchísimo más tedioso trabajandocon grandes cantidades de datos, dónde la hoja de cálculo es tan grande\
que no se puede ver y operar con todo lo relevante de una manera tan sencilla como se hace con Pandas.

### Ejercicio 2
¿Qué es Pandas?

Pandas se trata de una librería disponible en Python 3 que contiene una serie de funciones, métodos, objetos, etc, que son muy útiles para trabajar\
con dataframes con grandes cantidades de datos.

### Ejercicio 3
Diferencia entre los métodos **.iloc()** y **.loc()**

El método **.iloc()** sirve para filtrar filas y columnas concretas de un dataframe, pero, haciendo uso para ello\
del índice de estas filas y columnas. Mientras, el método **.loc()** sirve para filtrar filas y columnas, pero en este caso, haciendo uso de las etiquetas de estas.

### Ejercicio 4
¿Para qué se usa groupby?

**groupby** sirve para agrupar ciertas columnas, cuyas claves son pasadas como parámetro del método.

### **EJERCICIOS PRÁCTICOS**

### Ejercicio 1
Visualiza los 25 primeros valores de la columna 'cc'

In [1]:
# Antes de la realización del primer ejercicio, se necesita:
# Importar la librería
# Importar el dataframe

import pandas as pd

data = pd.read_csv('https://raw.githubusercontent.com/SerDiaz/Introduccion_programacion_en_python/main/dia3/REE_hist_Tenerife.csv', sep=',', index_col=0)

# Imprimimos el dataframe para comprobar que ha sido importado de manera correcta
data

,cc,day,dem,die,ele,em_cc,em_die,em_ele,em_gas,em_vap,...,gas,hid,hour,minute,month,pre,pro,vap,week,year
0,260.2,31,546.4,38.0,0.0,26.02,4.116667,0.0,8.0784,29.430,...,43.2,0.0,20,0,12,551.0,539.6,196.2,1,2012
1,259.2,31,544.8,38.0,0.0,25.92,4.116667,0.0,7.8166,29.325,...,41.8,0.0,20,10,12,545.1,539.6,195.5,1,2012
2,256.2,31,540.3,38.0,0.0,25.62,4.116667,0.0,7.6109,29.265,...,40.7,0.0,20,20,12,540.7,539.6,195.1,1,2012
3,253.4,31,535.1,38.0,0.0,25.34,4.116667,0.0,7.5548,29.205,...,40.4,0.0,20,30,12,537.8,539.6,194.7,1,2012
4,248.6,31,531.2,38.0,0.0,24.86,4.116667,0.0,7.2930,29.100,...,39.0,0.0,20,40,12,536.2,539.6,194.0,1,2012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343,154.0,18,338.9,37.8,0.0,15.40,4.095000,0.0,1.6082,17.925,...,8.6,0.0,23,0,10,343.4,330.3,119.5,42,2020
344,160.9,18,329.2,37.9,0.0,16.09,4.105833,0.0,0.2805,16.290,...,1.5,0.0,23,10,10,335.3,330.3,108.6,42,2020
345,156.8,18,325.5,38.2,0.0,15.68,4.138333,0.0,0.0000,16.695,...,0.0,0.0,23,20,10,328.1,330.3,111.3,42,2020
346,156.5,18,319.9,37.8,0.0,15.65,4.095000,0.0,0.0000,16.725,...,0.0,0.0,23,30,10,321.7,330.3,111.5,42,2020
347,0.0,18,313.0,0.0,0.0,0.00,0.000000,0.0,0.0000,0.000,...,0.0,0.0,23,40,10,316.2,330.3,0.0,42,2020

In [2]:
# Reinicializamos los índices de las filas del datafram
data = data.reset_index()

data

,index,cc,day,dem,die,ele,em_cc,em_die,em_ele,em_gas,...,gas,hid,hour,minute,month,pre,pro,vap,week,year
0,0,260.2,31,546.4,38.0,0.0,26.02,4.116667,0.0,8.0784,...,43.2,0.0,20,0,12,551.0,539.6,196.2,1,2012
1,1,259.2,31,544.8,38.0,0.0,25.92,4.116667,0.0,7.8166,...,41.8,0.0,20,10,12,545.1,539.6,195.5,1,2012
2,2,256.2,31,540.3,38.0,0.0,25.62,4.116667,0.0,7.6109,...,40.7,0.0,20,20,12,540.7,539.6,195.1,1,2012
3,3,253.4,31,535.1,38.0,0.0,25.34,4.116667,0.0,7.5548,...,40.4,0.0,20,30,12,537.8,539.6,194.7,1,2012
4,4,248.6,31,531.2,38.0,0.0,24.86,4.116667,0.0,7.2930,...,39.0,0.0,20,40,12,536.2,539.6,194.0,1,2012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409989,343,154.0,18,338.9,37.8,0.0,15.40,4.095000,0.0,1.6082,...,8.6,0.0,23,0,10,343.4,330.3,119.5,42,2020
409990,344,160.9,18,329.2,37.9,0.0,16.09,4.105833,0.0,0.2805,...,1.5,0.0,23,10,10,335.3,330.3,108.6,42,2020
409991,345,156.8,18,325.5,38.2,0.0,15.68,4.138333,0.0,0.0000,...,0.0,0.0,23,20,10,328.1,330.3,111.3,42,2020
409992,346,156.5,18,319.9,37.8,0.0,15.65,4.095000,0.0,0.0000,...,0.0,0.0,23,30,10,321.7,330.3,111.5,42,2020
409993,347,0.0,18,313.0,0.0,0.0,0.00,0.000000,0.0,0.0000,...,0.0,0.0,23,40,10,316.2,330.3,0.0,42,2020

In [3]:
# Eliminamos la columna de índices
del data['index']

data

,cc,day,dem,die,ele,em_cc,em_die,em_ele,em_gas,em_vap,...,gas,hid,hour,minute,month,pre,pro,vap,week,year
0,260.2,31,546.4,38.0,0.0,26.02,4.116667,0.0,8.0784,29.430,...,43.2,0.0,20,0,12,551.0,539.6,196.2,1,2012
1,259.2,31,544.8,38.0,0.0,25.92,4.116667,0.0,7.8166,29.325,...,41.8,0.0,20,10,12,545.1,539.6,195.5,1,2012
2,256.2,31,540.3,38.0,0.0,25.62,4.116667,0.0,7.6109,29.265,...,40.7,0.0,20,20,12,540.7,539.6,195.1,1,2012
3,253.4,31,535.1,38.0,0.0,25.34,4.116667,0.0,7.5548,29.205,...,40.4,0.0,20,30,12,537.8,539.6,194.7,1,2012
4,248.6,31,531.2,38.0,0.0,24.86,4.116667,0.0,7.2930,29.100,...,39.0,0.0,20,40,12,536.2,539.6,194.0,1,2012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409989,154.0,18,338.9,37.8,0.0,15.40,4.095000,0.0,1.6082,17.925,...,8.6,0.0,23,0,10,343.4,330.3,119.5,42,2020
409990,160.9,18,329.2,37.9,0.0,16.09,4.105833,0.0,0.2805,16.290,...,1.5,0.0,23,10,10,335.3,330.3,108.6,42,2020
409991,156.8,18,325.5,38.2,0.0,15.68,4.138333,0.0,0.0000,16.695,...,0.0,0.0,23,20,10,328.1,330.3,111.3,42,2020
409992,156.5,18,319.9,37.8,0.0,15.65,4.095000,0.0,0.0000,16.725,...,0.0,0.0,23,30,10,321.7,330.3,111.5,42,2020
409993,0.0,18,313.0,0.0,0.0,0.00,0.000000,0.0,0.0000,0.000,...,0.0,0.0,23,40,10,316.2,330.3,0.0,42,2020

In [4]:
# Ejercicio 1
data.loc[0:25,'cc']

0     260.2
1     259.2
2     256.2
3     253.4
4     248.6
5     243.5
6     240.7
7     235.3
8     230.5
9     221.1
10    201.9
11    188.3
12    188.1
13    184.9
14    185.7
15    182.6
16    182.0
17    176.9
18    173.8
19    175.6
20    177.6
21    175.8
22    176.0
23    174.0
24    170.0
25    168.1
Name: cc, dtype: float64

### Ejercicio 2
Muestra todos las filas donde el día se mayor a 10

In [5]:
# Ejercicio 2
data[(data['day'] >= 10)]

,cc,day,dem,die,ele,em_cc,em_die,em_ele,em_gas,em_vap,...,gas,hid,hour,minute,month,pre,pro,vap,week,year
0,260.2,31,546.4,38.0,0.0,26.02,4.116667,0.0,8.0784,29.430,...,43.2,0.0,20,0,12,551.0,539.6,196.2,1,2012
1,259.2,31,544.8,38.0,0.0,25.92,4.116667,0.0,7.8166,29.325,...,41.8,0.0,20,10,12,545.1,539.6,195.5,1,2012
2,256.2,31,540.3,38.0,0.0,25.62,4.116667,0.0,7.6109,29.265,...,40.7,0.0,20,20,12,540.7,539.6,195.1,1,2012
3,253.4,31,535.1,38.0,0.0,25.34,4.116667,0.0,7.5548,29.205,...,40.4,0.0,20,30,12,537.8,539.6,194.7,1,2012
4,248.6,31,531.2,38.0,0.0,24.86,4.116667,0.0,7.2930,29.100,...,39.0,0.0,20,40,12,536.2,539.6,194.0,1,2012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409989,154.0,18,338.9,37.8,0.0,15.40,4.095000,0.0,1.6082,17.925,...,8.6,0.0,23,0,10,343.4,330.3,119.5,42,2020
409990,160.9,18,329.2,37.9,0.0,16.09,4.105833,0.0,0.2805,16.290,...,1.5,0.0,23,10,10,335.3,330.3,108.6,42,2020
409991,156.8,18,325.5,38.2,0.0,15.68,4.138333,0.0,0.0000,16.695,...,0.0,0.0,23,20,10,328.1,330.3,111.3,42,2020
409992,156.5,18,319.9,37.8,0.0,15.65,4.095000,0.0,0.0000,16.725,...,0.0,0.0,23,30,10,321.7,330.3,111.5,42,2020
409993,0.0,18,313.0,0.0,0.0,0.00,0.000000,0.0,0.0000,0.000,...,0.0,0.0,23,40,10,316.2,330.3,0.0,42,2020

### Ejercicio 3
Queremos los datos del 20 de septimbre de 2015

In [6]:
# Ejercicio 3
data[(data['day'] == 20) & (data['month'] == 9) & (data['year'] == 2015)]

,cc,day,dem,die,ele,em_cc,em_die,em_ele,em_gas,em_vap,...,gas,hid,hour,minute,month,pre,pro,vap,week,year
142829,162.5,20,341.2,36.9,0.0,16.25,3.997500,0.0,0.0,21.090,...,0.0,0.0,0,0,9,343.9,325.4,140.6,38,2015
142830,162.6,20,332.3,36.5,0.0,16.26,3.954167,0.0,0.0,19.695,...,0.0,0.0,0,10,9,336.9,325.4,131.3,38,2015
142831,163.4,20,327.8,36.9,0.0,16.34,3.997500,0.0,0.0,18.795,...,0.0,0.0,0,20,9,330.5,325.4,125.3,38,2015
142832,162.2,20,324.1,37.3,0.0,16.22,4.040833,0.0,0.0,18.375,...,0.0,0.0,0,30,9,324.6,325.4,122.5,38,2015
142833,164.9,20,318.6,37.0,0.0,16.49,4.008333,0.0,0.0,17.385,...,0.0,0.0,0,40,9,319.2,325.4,115.9,38,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142968,164.9,20,368.9,38.4,0.0,16.49,4.160000,0.0,0.0,24.480,...,0.0,0.0,23,10,9,359.7,348.5,163.2,38,2015
142969,163.7,20,362.0,39.1,0.0,16.37,4.235833,0.0,0.0,23.505,...,0.0,0.0,23,20,9,352.3,348.5,156.7,38,2015
142970,162.3,20,354.9,37.8,0.0,16.23,4.095000,0.0,0.0,22.470,...,0.0,0.0,23,30,9,346.3,348.5,149.8,38,2015
142971,162.8,20,348.3,38.1,0.0,16.28,4.127500,0.0,0.0,21.765,...,0.0,0.0,23,40,9,341.8,348.5,145.1,38,2015
142972,163.9,20,341.9,38.0,0.0,16.39,4.116667,0.0,0.0,20.865,...,0.0,0.0,23,50,9,338.8,348.5,139.1,38,2015

### Ejercicio 4
Escribir un código con iloc que permita seleccionar las filas 1, 3 y 5 y sólo la columna 3.

In [7]:
# Ejercicio 4
data.iloc[[1,3,5],3]

1    38.0
3    38.0
5    38.0
Name: die, dtype: float64

### Ejercicio 5
Copia el dataframe principal y borra la columna hid porque no nos interesa. Luego imprime usando loc las filas de 10 a 20 de las columnas demanda, demanda programada y demanda prevista.

In [8]:
# Ejercicio 5
data_copy = data.copy()

del data_copy['hid']

data_copy.loc[10:20,['dem','pro','pre']]

      dem    pro    pre
10  468.0  518.8  511.9
11  457.7  518.8  494.9
12  447.5  424.2  473.6
13  436.3  424.2  451.9
14  423.0  424.2  433.7
15  416.7  424.2  419.0
16  409.5  424.2  407.8
17  402.5  424.2  400.0
18  396.8  386.7  395.7
19  391.5  386.7  393.1
20  388.9  386.7  390.2

### Ejercicio 6
Queremos obtener la energía fotovoltaica y la energía eólica de los años 2016, 2017 y 2018.

In [27]:
# Ejercicio 6
year_range1 = data_copy[(data_copy['year'] == 2016)]
year_range2 = data_copy[(data_copy['year']) == 2018]

data_copy.loc[year_range1:year_range2,['eol','fot']]
# Debería de funcionar de esta manera pero da error

TypeError: '<' not supported between instances of 'float' and 'str'